# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_generative_models.generative_base.ipynb (unless otherwise specified).

__all__ = ['GenerativeModel']

# Cell

from ..imports import *
from ..torch_imports import *
from ..torch_core import *
from ..layers import *

# Cell

class GenerativeModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        raise NotImplementedError

    def x_to_latent(self, x):
        raise NotImplementedError

    def sample(self, **sample_kwargs):
        raise NotImplementedError

    def sample_no_grad(self, **sample_kwargs):
        with torch.no_grad():
            return self.sample(**sample_kwargs)

    def get_rl_tensors(self):
        raise NotImplementedError