# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://DarkMatterAI.github.io/mrl/"

git_url = "https://github.com/DarkMatterAI/mrl/tree/main/"

def custom_doc_links(name): return None
