# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"is_container": "00_core.ipynb",
         "maybe_parallel": "00_core.ipynb",
         "to_mol": "01_chem.ipynb",
         "to_smile": "01_chem.ipynb"}

modules = ["core.py",
           "chem.py"]

doc_url = "https://DarkMatterAI.github.io/mrl/"

git_url = "https://github.com/DarkMatterAI/mrl/tree/main/"

def custom_doc_links(name): return None
