# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_torch_core.ipynb (unless otherwise specified).

__all__ = ['to_device', 'set_device', 'USE_CUDA']

# Cell
from .imports import *
from .torch_imports import *

# Cell

USE_CUDA = torch.cuda.is_available()

if USE_CUDA:
    torch.backends.cudnn.benchmark = True

def to_device(tensor, device=None):
    if device is None:
        if torch.cuda.is_available():
            device = int(os.environ.get('DEFAULT_GPU') or 0)
        else:
            device='cpu'

    device = torch.device(device)

    if hasattr(tensor, 'to'):
        output = tensor.to(device)
    else:
        output = [to_device(i, device) for i in tensor]

    return output

def set_device(device):
    os.environ['DEFAULT_GPU'] = device